on:
  schedule:
    - cron: 3 0 * * 5
  workflow_dispatch:

name: weekly-fantasypros

jobs:
  weekly-fantasypros:
    runs-on: ubuntu-24.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/noble/latest
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout private db repo
        uses: actions/checkout@v2
        with:
          path: private
          repository: dynastyprocess/db
          token: ${{ secrets.GH_PAT }}

      - name: Checkout public data repo
        uses: actions/checkout@v2
        with:
          path: public

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        id: install-r

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          working-directory: ./private
          extra-packages: ffverse/ffscrapr

      - name: Scrape FantasyPros
        working-directory: ./private
        run: |
          source("R/fantasypros/ecr-scraper.R", chdir = TRUE)
        shell: Rscript {0}

      - name: Save local data
        working-directory: ./private
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated FP scrape `date`" || echo "No changes to commit"
          git push origin main

      - name: Save public data
        working-directory: ./public
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add files
          git commit -m "Automated FP scrape `date`" || echo "No changes to commit"
          git push origin master

      - name: Upload log results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: scrape-logs
          path: ./private/fp-scrape-log.txt
